import { Toaster } from '@/components/ui/sonner'
import { UserProvider } from '@/lib/auth'
import retrieveUserFromSession from '@/utils/getUser'
import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import './globals.css'

const nunito = Nunito({
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const userPromise = retrieveUserFromSession()
  return (
    <html lang='en'>
      <body className={`${nunito.className}`} suppressHydrationWarning>
        <Toaster richColors closeButton />
        <UserProvider userPromise={userPromise}>{children}</UserProvider>
      </body>
    </html>
  )
}
